spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/skillsync_auth?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /auth/v3/api-docs

jwt:
  secret: ${JWT_SECRET:mysupersecuresecretkeywhichisatleast32characterslong}
  expiration: 3600000
  refresh-expiration: 86400000

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}
