spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/skillsync_auth?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

springdoc:
  api-docs:
    path: /auth/v3/api-docs

jwt:
  secret: mysupersecuresecretkeywhichisatleast32characterslong
  expiration: 86400000
  refresh-expiration: 604800000
