server:
  port: 8083

springdoc:
  api-docs:
    path: /mentors/v3/api-docs

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/mentor_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
logging:
  level:
    com.skillsync.mentorservice: DEBUG
