server:
  port: 8085

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/session_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /sessions/v3/api-docs
