server:
  port: 8084

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/skill_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /skills/v3/api-docs
